// This file is auto-generated by scripts/generate-custom-icons.cjs
// Do not edit manually. Edit the .svg files in this folder instead.

import { h } from "preact"

export type SvgProps = {
  color?: string
  opacity?: number
  title?: string
}

export function IconArrowCurvedDownRight16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M9.85341 12.8534C9.65814 13.0487 9.34163 13.0487 9.14638 12.8534C8.9756 12.6826 8.95379 12.4186 9.08192 12.2245L9.14638 12.1464L11.2929 9.99992H7.49989C5.01461 9.99987 2.99989 7.98513 2.99989 5.49992V3.49992C2.99995 3.22386 3.22383 2.99997 3.49989 2.99992C3.776 2.99992 3.99984 3.22383 3.99989 3.49992V5.49992C3.99989 7.43293 5.56698 8.99987 7.49989 8.99992H11.2929L9.14638 6.85344C8.95121 6.65817 8.95116 6.34164 9.14638 6.14641C9.31721 5.97558 9.58122 5.95387 9.77528 6.08195L9.85341 6.14641L12.8534 9.14641C13.0487 9.34167 13.0487 9.65818 12.8534 9.85344L9.85341 12.8534Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconArrowDown16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M4.14787 9.3539C3.95265 9.15862 3.9526 8.84211 4.14787 8.64687C4.34314 8.45181 4.65971 8.45171 4.8549 8.64687L7.00041 10.7934L7.00041 4.00039C7.00041 3.72425 7.22427 3.50039 7.50041 3.50039C7.77634 3.50063 8.00041 3.7244 8.00041 4.00039L8.00041 10.7934L10.1479 8.64687C10.3431 8.45182 10.6597 8.45172 10.8549 8.64687C11.0497 8.84211 11.0499 9.15876 10.8549 9.3539L7.85392 12.3539C7.65875 12.549 7.34215 12.5488 7.14689 12.3539L4.14787 9.3539Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconArrowLeft16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M6.64609 4.14787C6.84138 3.95264 7.15789 3.9526 7.35312 4.14787C7.54818 4.34314 7.54828 4.65971 7.35312 4.8549L5.20664 7.00041H11.9996C12.2757 7.00041 12.4996 7.22427 12.4996 7.50041C12.4994 7.77634 12.2756 8.0004 11.9996 8.00041H5.20664L7.35312 10.1479C7.54818 10.3431 7.54828 10.6597 7.35312 10.8549C7.15788 11.0497 6.84124 11.0499 6.64609 10.8549L3.64609 7.85392C3.45099 7.65875 3.45117 7.34215 3.64609 7.14689L6.64609 4.14787Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconArrowRight16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M9.35391 4.14787C9.15862 3.95264 8.84211 3.9526 8.64688 4.14787C8.45182 4.34314 8.45172 4.65971 8.64688 4.8549L10.7934 7.00041H4.00039C3.72425 7.00041 3.50039 7.22427 3.50039 7.50041C3.50064 7.77634 3.7244 8.0004 4.00039 8.00041H10.7934L8.64688 10.1479C8.45182 10.3431 8.45172 10.6597 8.64688 10.8549C8.84212 11.0497 9.15876 11.0499 9.35391 10.8549L12.3539 7.85392C12.549 7.65875 12.5488 7.34215 12.3539 7.14689L9.35391 4.14787Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconArrowUp16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M11.8521 6.6461C12.0474 6.84138 12.0474 7.15789 11.8521 7.35313C11.6569 7.54819 11.3403 7.54828 11.1451 7.35313L8.99959 5.20664L8.99959 11.9996C8.99959 12.2758 8.77573 12.4996 8.49959 12.4996C8.22366 12.4994 7.99959 12.2756 7.99959 11.9996L7.99959 5.20664L5.85213 7.35313C5.65686 7.54818 5.34029 7.54828 5.1451 7.35313C4.95026 7.15788 4.95014 6.84124 5.1451 6.6461L8.14608 3.6461C8.34125 3.45099 8.65785 3.45117 8.85311 3.6461L11.8521 6.6461Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconChevronDown16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M9.76731 6.76777C9.96257 6.5725 10.2801 6.5725 10.4753 6.76777C10.6702 6.96296 10.6702 7.2796 10.4753 7.4748L7.99973 9.94941L5.52512 7.4748C5.32986 7.27953 5.32986 6.96303 5.52512 6.76777C5.72039 6.5725 6.03689 6.5725 6.23216 6.76777L7.99973 8.53534L9.76731 6.76777Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconChevronLeft16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M9.23224 6.23269C9.4275 6.03743 9.4275 5.71994 9.23224 5.52468C9.03704 5.32976 8.7204 5.32976 8.5252 5.52468L6.05059 8.00027L8.5252 10.4749C8.72047 10.6701 9.03697 10.6701 9.23223 10.4749C9.4275 10.2796 9.4275 9.96311 9.23223 9.76785L7.46466 8.00027L9.23224 6.23269Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconChevronRight16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M6.76776 6.23269C6.5725 6.03743 6.5725 5.71994 6.76776 5.52468C6.96296 5.32976 7.2796 5.32976 7.47479 5.52468L9.9494 8.00027L7.47479 10.4749C7.27953 10.6701 6.96302 10.6701 6.76776 10.4749C6.5725 10.2796 6.5725 9.96311 6.76776 9.76785L8.53534 8.00027L6.76776 6.23269Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconChevronUp16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M6.23269 9.23223C6.03743 9.4275 5.71994 9.4275 5.52468 9.23223C5.32976 9.03704 5.32976 8.7204 5.52468 8.5252L8.00027 6.05059L10.4749 8.5252C10.6701 8.72047 10.6701 9.03697 10.4749 9.23223C10.2796 9.4275 9.96311 9.4275 9.76784 9.23223L8.00027 7.46466L6.23269 9.23223Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}

export function IconTarget16(props: SvgProps) {
  const color = props.color ?? "currentColor"
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-label={props.title}>
      <path d="M8 16C7.72386 16 7.5 15.7761 7.5 15.5V13.9775C4.58523 13.737 2.263 11.4148 2.02246 8.5H0.5C0.223858 8.5 9.42357e-08 8.27614 0 8C1.18377e-07 7.72386 0.223857 7.5 0.5 7.5H2.02246C2.263 4.58525 4.58527 2.26401 7.5 2.02344V0.5C7.5 0.223858 7.72386 0 8 0C8.27614 0 8.5 0.223858 8.5 0.5V2.02344C11.4147 2.26401 13.737 4.58525 13.9775 7.5H15.5C15.7761 7.5 16 7.72386 16 8C16 8.27614 15.7761 8.5 15.5 8.5H13.9775C13.737 11.4148 11.4148 13.737 8.5 13.9775V15.5C8.5 15.7761 8.27614 16 8 16ZM7.5 11.5C7.5 11.2239 7.72386 11 8 11C8.27614 11 8.5 11.2239 8.5 11.5V12.9756C10.8622 12.7411 12.7411 10.8622 12.9756 8.5H11.5C11.2239 8.5 11 8.27614 11 8C11 7.72386 11.2239 7.5 11.5 7.5H12.9756C12.7411 5.1378 10.8622 3.25996 8.5 3.02539V4.5C8.5 4.77614 8.27614 5 8 5C7.72386 5 7.5 4.77614 7.5 4.5V3.02539C5.13782 3.25996 3.25893 5.1378 3.02441 7.5H4.5C4.77614 7.5 5 7.72386 5 8C5 8.27614 4.77614 8.5 4.5 8.5H3.02441C3.25894 10.8622 5.13777 12.7411 7.5 12.9756V11.5Z" fill={color} fillOpacity={props.opacity ?? 0.9} />
    </svg>
  )
}
